# Reference:
# https://golangci-lint.run/docs/configuration/file/

version: "2"

linters:
  default: all
  disable:
    - ireturn # overly strict
    - paralleltest # not very helpful

    # to review
    - depguard
    - gomodguard # replaced by gomodguard_v2
    - mnd
    - testifylint
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - err113
          - funlen
          - goconst
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
