# Reference:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

version: 2

linters:
  enable-all: true
  disable:
    - ireturn # overly strict
    - paralleltest # not very helpful

    # deprecated/replaced
    - depguard
    - testifylint
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - goerr113
