name: "🧬 Mutation Tests"
on:
  workflow_run:
    workflows: [ "🧩 Continuous Integration" ]
    branches: [ main ]
    types:
      - completed

jobs:

  Mutation:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.15.0

      - name: "🧬 Mutation Tests"
        run: devbox run -- make test.mutation
